# Generated by Django 5.1.6 on 2025-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_stage_name_alter_stage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='color',
            field=models.CharField(default='#000', max_length=7),
        ),
    ]
