# Generated by Django 5.1.6 on 2025-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_stage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(default='#000', max_length=7),
        ),
    ]
