# Generated by Django 5.1.6 on 2025-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_stage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
